output_bucket: firespreadpredictiontest
rectangular_size: 0.5
year: 2012
fire_14659047:
  latitude: 53.48541871501316
  longitude: -123.04471847045988
  start: 2012-04-07
  end: 2012-04-20
fire_14918627:
  latitude: 60.232037146821575
  longitude: -125.68474863850548
  start: 2012-07-23
  end: 2012-07-26
fire_14918646:
  latitude: 59.51275893020594
  longitude: -123.69061583643844
  start: 2012-07-23
  end: 2012-08-03
fire_15190358:
  latitude: 59.01877100323858
  longitude: -120.5644665064968
  start: 2012-09-09
  end: 2012-09-30
fire_15190394:
  latitude: 57.87708529689047
  longitude: -123.94910030471252
  start: 2012-09-17
  end: 2012-09-29
fire_15046665:
  latitude: 58.35483364422728
  longitude: -122.09188330319655
  start: 2012-08-08
  end: 2012-08-31
fire_15046663:
  latitude: 58.38812798926059
  longitude: -126.19352386438148
  start: 2012-08-16
  end: 2012-08-27
fire_14918640:
  latitude: 59.588053436199864
  longitude: -123.61663873251142
  start: 2012-07-22
  end: 2012-08-08
fire_14918688:
  latitude: 58.8704019532266
  longitude: -121.200877215599
  start: 2012-07-10
  end: 2012-07-14
fire_15046684:
  latitude: 57.58514662913765
  longitude: -120.06177608815872
  start: 2012-08-10
  end: 2012-08-27
fire_14918632:
  latitude: 59.78388458376348
  longitude: -120.76366592569968
  start: 2012-07-05
  end: 2012-08-12
fire_15046599:
  latitude: 59.89502844674829
  longitude: -124.81000913537824
  start: 2012-08-17
  end: 2012-08-21
fire_15190382:
  latitude: 58.33911263922894
  longitude: -122.01738785351188
  start: 2012-09-14
  end: 2012-09-26
fire_15046632:
  latitude: 59.471198220250656
  longitude: -129.0540822035589
  start: 2012-08-13
  end: 2012-08-23
fire_15190416:
  latitude: 57.543847466723456
  longitude: -120.07035286135566
  start: 2012-09-10
  end: 2012-09-28
fire_15046651:
  latitude: 59.24681930230268
  longitude: -127.64328077425
  start: 2012-08-09
  end: 2012-08-24
fire_14659039:
  latitude: 53.91890007318613
  longitude: -126.06692345376231
  start: 2012-04-17
  end: 2012-04-26
fire_15188297:
  latitude: 53.19001447406136
  longitude: -125.54512289484076
  start: 2012-09-02
  end: 2012-09-24
