output_bucket: firespreadpredictiontest
rectangular_size: 0.5
year: 2004
fire_5002856:
  latitude: 58.939935466183144
  longitude: -123.55635613728596
  start: 2004-09-22
  end: 2004-10-05
fire_4599837:
  latitude: 59.82297500544902
  longitude: -131.5085564708652
  start: 2004-06-21
  end: 2004-07-13
fire_4829570:
  latitude: 52.06067978222656
  longitude: -118.38142455439832
  start: 2004-08-18
  end: 2004-08-30
fire_4832030:
  latitude: 59.866802451370816
  longitude: -119.9342885841432
  start: 2004-08-08
  end: 2004-08-29
fire_4599888:
  latitude: 57.783128989688855
  longitude: -128.0036352519292
  start: 2004-06-25
  end: 2004-07-09
fire_4599804:
  latitude: 60.38749111706473
  longitude: -126.10244966038442
  start: 2004-06-25
  end: 2004-07-13
fire_4599829:
  latitude: 59.95858504682271
  longitude: -127.21031374386898
  start: 2004-06-25
  end: 2004-07-11
fire_4599824:
  latitude: 60.284445812331946
  longitude: -126.77437794298318
  start: 2004-06-25
  end: 2004-07-18
fire_4702774:
  latitude: 59.99801868543764
  longitude: -126.96931196418542
  start: 2004-07-19
  end: 2004-08-04
fire_4337386:
  latitude: 52.51263422329724
  longitude: -122.3403019751984
  start: 2004-03-09
  end: 2004-03-28
fire_4431406:
  latitude: 52.20309326997443
  longitude: -121.17227206734763
  start: 2004-04-12
  end: 2004-04-29
fire_4599881:
  latitude: 58.05940280654274
  longitude: -128.84609673146517
  start: 2004-06-19
  end: 2004-07-04
fire_4829515:
  latitude: 52.47385740354438
  longitude: -120.29327508652524
  start: 2004-08-16
  end: 2004-09-08
fire_4599840:
  latitude: 59.79192852935432
  longitude: -130.7627371952285
  start: 2004-06-23
  end: 2004-06-27
fire_4702769:
  latitude: 60.05765387680437
  longitude: -127.39148292312692
  start: 2004-07-17
  end: 2004-07-31
fire_4832010:
  latitude: 60.04208155137676
  longitude: -126.87247322238916
  start: 2004-08-10
  end: 2004-08-24
fire_4599869:
  latitude: 58.561046753803176
  longitude: -128.7621806328094
  start: 2004-06-27
  end: 2004-07-07
fire_4831997:
  latitude: 60.29693296016358
  longitude: -126.04194432298208
  start: 2004-08-09
  end: 2004-08-27
fire_4832002:
  latitude: 60.25403026034185
  longitude: -126.65644795427492
  start: 2004-08-09
  end: 2004-08-27
fire_4340909:
  latitude: 56.19068477057053
  longitude: -121.88619052755897
  start: 2004-03-24
  end: 2004-04-01
fire_4599890:
  latitude: 57.52748666941784
  longitude: -129.3539624017604
  start: 2004-06-24
  end: 2004-07-07
fire_4832075:
  latitude: 58.99704382400178
  longitude: -120.70377660327246
  start: 2004-08-11
  end: 2004-09-01
fire_4829480:
  latitude: 52.98827805976242
  longitude: -118.85489916072171
  start: 2004-08-11
  end: 2004-08-29
fire_4832067:
  latitude: 59.53906124874201
  longitude: -122.7716786733014
  start: 2004-08-05
  end: 2004-08-24
fire_4599856:
  latitude: 59.602917537529535
  longitude: -128.57141053612503
  start: 2004-06-22
  end: 2004-07-13
fire_4599873:
  latitude: 58.43833807634317
  longitude: -128.95625852474254
  start: 2004-06-22
  end: 2004-07-04
fire_4598273:
  latitude: 53.55532085581715
  longitude: -124.23069039271236
  start: 2004-06-22
  end: 2004-07-02
fire_4699319:
  latitude: 52.44361558832785
  longitude: -120.40499885925875
  start: 2004-07-26
  end: 2004-08-05
fire_4598278:
  latitude: 53.06243240344814
  longitude: -124.58872107607144
  start: 2004-06-21
  end: 2004-07-03
fire_4598270:
  latitude: 53.6361751764036
  longitude: -124.90464968088476
  start: 2004-06-21
  end: 2004-07-04
fire_4699336:
  latitude: 51.786404205698226
  longitude: -125.19504255255134
  start: 2004-07-29
  end: 2004-08-12
fire_4337387:
  latitude: 52.13848601858136
  longitude: -123.9300725820985
  start: 2004-03-09
  end: 2004-03-28
fire_4699337:
  latitude: 51.77232231268712
  longitude: -125.32599075735487
  start: 2004-07-22
  end: 2004-08-05
fire_4337398:
  latitude: 50.14721055984709
  longitude: -120.876678635737
  start: 2004-03-03
  end: 2004-03-16
fire_4699326:
  latitude: 52.19487995142122
  longitude: -125.59985378727096
  start: 2004-07-21
  end: 2004-08-16
fire_4598276:
  latitude: 53.11241084007523
  longitude: -126.58038855324408
  start: 2004-06-20
  end: 2004-06-27
fire_4598284:
  latitude: 52.952989339773715
  longitude: -126.302419037644
  start: 2004-06-20
  end: 2004-07-04
fire_4829609:
  latitude: 50.72817234487477
  longitude: -122.39611024119012
  start: 2004-08-11
  end: 2004-08-30
fire_4598316:
  latitude: 50.72746323925199
  longitude: -121.96904850865889
  start: 2004-06-18
  end: 2004-06-24
