output_bucket: firespreadpredictiontest
rectangular_size: 0.5
year: 2014
fire_17481861:
  latitude: 58.15397328180986
  longitude: -130.7109235846219
  start: 2014-09-20
  end: 2014-09-30
fire_17004606:
  latitude: 52.87716059309453
  longitude: -122.93157317166232
  start: 2014-04-08
  end: 2014-04-22
fire_17226879:
  latitude: 56.3907759041923
  longitude: -124.78105654668389
  start: 2014-07-13
  end: 2014-07-27
fire_17078503:
  latitude: 56.82883306184622
  longitude: -125.69562427600906
  start: 2014-05-27
  end: 2014-06-08
fire_17348985:
  latitude: 57.4990234430287
  longitude: -121.94214018546
  start: 2014-08-12
  end: 2014-08-24
fire_17348988:
  latitude: 57.35450781838502
  longitude: -120.40803933722454
  start: 2014-08-12
  end: 2014-08-27
fire_17226425:
  latitude: 50.19997142690947
  longitude: -115.65968842981184
  start: 2014-07-29
  end: 2014-08-10
fire_17226846:
  latitude: 56.846650627065145
  longitude: -125.489367251538
  start: 2014-07-09
  end: 2014-08-27
fire_17226875:
  latitude: 56.337039516258535
  longitude: -125.0428302204503
  start: 2014-07-09
  end: 2014-08-23
fire_17004596:
  latitude: 53.211702472858335
  longitude: -123.75086789418113
  start: 2014-04-12
  end: 2014-04-22
fire_17349075:
  latitude: 55.924828415469015
  longitude: -122.23372406938384
  start: 2014-08-17
  end: 2014-08-26
fire_17349074:
  latitude: 55.94846946684534
  longitude: -122.35743610726855
  start: 2014-08-17
  end: 2014-08-28
fire_17349060:
  latitude: 56.159748366496295
  longitude: -125.05971402187645
  start: 2014-08-05
  end: 2014-08-17
fire_17349006:
  latitude: 56.800252967144786
  longitude: -125.53520031643822
  start: 2014-08-01
  end: 2014-08-19
fire_17226924:
  latitude: 55.836809543624874
  longitude: -122.41603296399327
  start: 2014-07-12
  end: 2014-08-25
fire_17349024:
  latitude: 56.37151544890445
  longitude: -123.37365047161312
  start: 2014-08-04
  end: 2014-08-26
fire_17348975:
  latitude: 59.04545416120438
  longitude: -128.4231733678242
  start: 2014-08-04
  end: 2014-08-17
fire_17349009:
  latitude: 56.76966319923851
  longitude: -125.72842438496394
  start: 2014-08-04
  end: 2014-08-23
fire_17226349:
  latitude: 54.88945293694705
  longitude: -123.85882211781994
  start: 2014-07-15
  end: 2014-07-24
fire_17004569:
  latitude: 54.18036794237579
  longitude: -123.14604344744366
  start: 2014-04-13
  end: 2014-04-29
fire_17349089:
  latitude: 55.29740551610316
  longitude: -122.47481803657656
  start: 2014-08-15
  end: 2014-08-26
fire_17226937:
  latitude: 54.59333040633096
  longitude: -120.20523774679772
  start: 2014-07-02
  end: 2014-08-03
fire_17226394:
  latitude: 53.16637666055436
  longitude: -124.24365628058628
  start: 2014-07-05
  end: 2014-07-26
fire_17348081:
  latitude: 53.02612423938889
  longitude: -124.20208610048016
  start: 2014-08-18
  end: 2014-09-05
fire_17226351:
  latitude: 53.3045204578485
  longitude: -125.56386481019064
  start: 2014-07-09
  end: 2014-09-20
fire_17348078:
  latitude: 53.10956507480874
  longitude: -124.2000600081998
  start: 2014-08-09
  end: 2014-08-18
fire_17004625:
  latitude: 51.45816124411137
  longitude: -123.3632115398581
  start: 2014-04-11
  end: 2014-04-30
fire_17348036:
  latitude: 54.3639855053749
  longitude: -126.35235376515745
  start: 2014-08-12
  end: 2014-08-20
fire_17226356:
  latitude: 53.386566496385555
  longitude: -126.84701751361094
  start: 2014-07-14
  end: 2014-07-20
