output_bucket: firespreadpredictiontest
rectangular_size: 0.5
year: 2010
fire_12590011:
  latitude: 58.67482612495692
  longitude: -127.62523432808185
  start: 2010-08-15
  end: 2010-08-28
fire_12464455:
  latitude: 52.477471371583825
  longitude: -122.54705677611048
  start: 2010-07-28
  end: 2010-08-11
fire_12465544:
  latitude: 59.79664790034999
  longitude: -129.19616716323011
  start: 2010-07-28
  end: 2010-08-30
fire_12464438:
  latitude: 53.25204311504265
  longitude: -123.537175228725
  start: 2010-07-28
  end: 2010-09-02
fire_12372115:
  latitude: 57.99055270561433
  longitude: -130.6599833440538
  start: 2010-06-18
  end: 2010-07-02
fire_12371574:
  latitude: 53.84338025070934
  longitude: -124.32028575884766
  start: 2010-06-18
  end: 2010-07-06
fire_12372098:
  latitude: 59.10298704699462
  longitude: -131.56442699685334
  start: 2010-06-18
  end: 2010-07-04
fire_12464452:
  latitude: 52.79505699038323
  longitude: -123.1172000730832
  start: 2010-07-27
  end: 2010-08-11
fire_12372108:
  latitude: 58.20606874136117
  longitude: -131.85201829133888
  start: 2010-06-17
  end: 2010-08-22
fire_12372110:
  latitude: 58.18776665713717
  longitude: -130.29690951706576
  start: 2010-06-17
  end: 2010-06-30
fire_12590002:
  latitude: 59.461281876901104
  longitude: -128.2736319877005
  start: 2010-08-04
  end: 2010-08-20
fire_12590021:
  latitude: 58.14926863485481
  longitude: -131.72319426368333
  start: 2010-08-12
  end: 2010-08-31
fire_12590041:
  latitude: 57.940495588728986
  longitude: -130.60559916386072
  start: 2010-08-12
  end: 2010-08-29
fire_12587207:
  latitude: 53.33468841569922
  longitude: -123.969845183263
  start: 2010-08-15
  end: 2010-08-23
fire_12587269:
  latitude: 53.050753239511145
  longitude: -126.05415422365756
  start: 2010-08-15
  end: 2010-08-26
fire_12587324:
  latitude: 52.64407676945407
  longitude: -124.99688631533984
  start: 2010-08-11
  end: 2010-08-27
fire_12587198:
  latitude: 53.485304815181145
  longitude: -126.25888974130292
  start: 2010-08-11
  end: 2010-08-29
fire_12464483:
  latitude: 52.043051560161494
  longitude: -123.49902802946784
  start: 2010-07-26
  end: 2010-08-24
fire_12464448:
  latitude: 53.02475110470814
  longitude: -126.20815636740814
  start: 2010-07-09
  end: 2010-07-22
fire_12464511:
  latitude: 50.90929016498584
  longitude: -122.3208513238242
  start: 2010-07-17
  end: 2010-08-05
fire_12587238:
  latitude: 53.14250734329613
  longitude: -126.1778825496677
  start: 2010-08-09
  end: 2010-08-30
fire_12587333:
  latitude: 52.56431317322513
  longitude: -125.7410989197137
  start: 2010-08-09
  end: 2010-08-30
fire_12587106:
  latitude: 54.19484909116407
  longitude: -127.17926600673889
  start: 2010-08-09
  end: 2010-08-28
fire_12587124:
  latitude: 54.132094346072776
  longitude: -126.66502740434532
  start: 2010-08-17
  end: 2010-09-01
fire_12464465:
  latitude: 52.326673857380385
  longitude: -122.71423520643454
  start: 2010-07-28
  end: 2010-08-11
fire_12464478:
  latitude: 52.13729719145771
  longitude: -123.44126120618364
  start: 2010-07-28
  end: 2010-08-11
fire_12464467:
  latitude: 52.27479352895108
  longitude: -123.37057827183672
  start: 2010-07-28
  end: 2010-08-27
fire_12464458:
  latitude: 52.39245702755339
  longitude: -122.8177661400205
  start: 2010-07-28
  end: 2010-08-23
fire_12464435:
  latitude: 53.82491280584287
  longitude: -125.14945339566704
  start: 2010-07-28
  end: 2010-09-02
fire_12464479:
  latitude: 52.081571280507205
  longitude: -122.43014651422304
  start: 2010-07-28
  end: 2010-09-01
fire_12234922:
  latitude: 49.9811930464922
  longitude: -120.01079540500032
  start: 2010-04-11
  end: 2010-04-28
fire_12143722:
  latitude: 51.52896385960029
  longitude: -122.69151628088042
  start: 2010-03-10
  end: 2010-03-25
fire_12587299:
  latitude: 52.76181942629028
  longitude: -126.48989652747623
  start: 2010-08-13
  end: 2010-09-03
fire_12587141:
  latitude: 54.002993595815674
  longitude: -126.74922641502955
  start: 2010-08-13
  end: 2010-09-01
fire_12464449:
  latitude: 53.01346583457333
  longitude: -126.1518893847448
  start: 2010-07-24
  end: 2010-08-06
fire_12464501:
  latitude: 51.6426077101512
  longitude: -122.07135002048273
  start: 2010-07-24
  end: 2010-08-09
fire_12464444:
  latitude: 53.13651208895713
  longitude: -126.15319132555383
  start: 2010-07-27
  end: 2010-08-06
fire_12587266:
  latitude: 53.01791222252517
  longitude: -124.94182373639438
  start: 2010-08-04
  end: 2010-09-01
fire_12464454:
  latitude: 52.7025011761224
  longitude: -123.36297706332984
  start: 2010-07-31
  end: 2010-08-11
