output_bucket: firespreadpredictiontest
rectangular_size: 0.5
year: 2006
fire_7265860:
  latitude: 58.222299378088614
  longitude: -125.86532532378492
  start: 2006-06-13
  end: 2006-07-21
fire_7035674:
  latitude: 52.934029353200685
  longitude: -122.79821515182772
  start: 2006-03-21
  end: 2006-03-31
fire_7354561:
  latitude: 60.1565883347677
  longitude: -126.59759857654012
  start: 2006-07-15
  end: 2006-08-04
fire_7354685:
  latitude: 56.182314505180045
  longitude: -124.95210857897648
  start: 2006-07-03
  end: 2006-07-07
fire_7354555:
  latitude: 60.17314218901201
  longitude: -126.80825063528177
  start: 2006-07-03
  end: 2006-07-18
fire_7035678:
  latitude: 52.17931473572214
  longitude: -121.55581341057776
  start: 2006-03-20
  end: 2006-03-28
fire_7035685:
  latitude: 51.451235393607995
  longitude: -121.23777490571904
  start: 2006-03-20
  end: 2006-03-31
fire_7354643:
  latitude: 57.37015312212946
  longitude: -121.83685859055292
  start: 2006-07-02
  end: 2006-07-12
fire_7353735:
  latitude: 53.56736755412011
  longitude: -119.59421924696076
  start: 2006-07-02
  end: 2006-07-20
fire_7035673:
  latitude: 53.2683974398291
  longitude: -122.55382178415432
  start: 2006-03-24
  end: 2006-04-02
fire_7353757:
  latitude: 53.02543298245425
  longitude: -123.34027114419403
  start: 2006-07-01
  end: 2006-07-10
fire_7354773:
  latitude: 54.58471909390546
  longitude: -120.604118023291
  start: 2006-07-01
  end: 2006-07-10
fire_7354765:
  latitude: 54.76921359976885
  longitude: -120.42841536932416
  start: 2006-07-01
  end: 2006-07-15
fire_7265504:
  latitude: 54.41315925633827
  longitude: -120.61632743517264
  start: 2006-06-27
  end: 2006-07-15
fire_7265898:
  latitude: 56.96751573883662
  longitude: -121.85615036036975
  start: 2006-06-27
  end: 2006-07-14
fire_7035688:
  latitude: 51.05405262745007
  longitude: -120.80584446885617
  start: 2006-03-22
  end: 2006-04-12
fire_7265851:
  latitude: 58.64176734768253
  longitude: -127.70253063586746
  start: 2006-06-26
  end: 2006-07-23
fire_7265884:
  latitude: 57.46585541030529
  longitude: -121.7985681602188
  start: 2006-06-26
  end: 2006-07-14
fire_7353693:
  latitude: 56.05898791608177
  longitude: -125.3248134337218
  start: 2006-07-04
  end: 2006-07-15
fire_7265948:
  latitude: 55.22038146526106
  longitude: -120.82830522097792
  start: 2006-06-30
  end: 2006-07-10
fire_7265878:
  latitude: 57.63160016906916
  longitude: -122.86898464542588
  start: 2006-06-30
  end: 2006-07-19
fire_7265838:
  latitude: 60.382117828345095
  longitude: -126.46491263657744
  start: 2006-06-30
  end: 2006-08-05
fire_7265856:
  latitude: 58.5815000878756
  longitude: -127.6982406276093
  start: 2006-06-30
  end: 2006-07-12
fire_7035675:
  latitude: 52.504465798019616
  longitude: -125.29784754286186
  start: 2006-03-20
  end: 2006-04-01
fire_7353748:
  latitude: 53.11373480652534
  longitude: -124.0852730813032
  start: 2006-07-02
  end: 2006-07-13
fire_7353741:
  latitude: 53.52967126399633
  longitude: -124.93229493018838
  start: 2006-07-02
  end: 2006-07-16
fire_7353776:
  latitude: 52.83694537241841
  longitude: -125.45649718182374
  start: 2006-07-01
  end: 2006-07-15
fire_7353772:
  latitude: 52.94007460450465
  longitude: -123.9606109990038
  start: 2006-07-05
  end: 2006-07-10
