output_bucket: firespreadpredictiontest
rectangular_size: 0.5
year: 2009
fire_10992044:
  latitude: 50.35851075514754
  longitude: -120.18537449608354
  start: 2009-04-10
  end: 2009-04-24
fire_10992024:
  latitude: 51.971139040944465
  longitude: -121.37346179956062
  start: 2009-04-10
  end: 2009-04-27
fire_11253583:
  latitude: 50.11748974618661
  longitude: -119.63748988906424
  start: 2009-07-15
  end: 2009-08-18
fire_11255113:
  latitude: 56.829505490951355
  longitude: -126.18580382715804
  start: 2009-07-27
  end: 2009-08-07
fire_11255102:
  latitude: 58.74535605031544
  longitude: -127.68002101195798
  start: 2009-07-31
  end: 2009-08-08
fire_11386069:
  latitude: 50.61279110091992
  longitude: -119.75408855178208
  start: 2009-08-28
  end: 2009-09-03
fire_10992038:
  latitude: 51.45323750565386
  longitude: -121.1482658490936
  start: 2009-04-05
  end: 2009-04-17
fire_11255088:
  latitude: 60.099322514990696
  longitude: -132.95548495347998
  start: 2009-07-30
  end: 2009-08-11
fire_11255110:
  latitude: 57.5196613748758
  longitude: -127.5959887345122
  start: 2009-07-30
  end: 2009-08-30
fire_10991983:
  latitude: 54.38929722746936
  longitude: -124.216664142659
  start: 2009-04-17
  end: 2009-05-01
fire_11253561:
  latitude: 51.31575230896062
  longitude: -119.27543858132712
  start: 2009-07-25
  end: 2009-08-10
fire_11387834:
  latitude: 58.10051408235935
  longitude: -127.14752998323168
  start: 2009-08-01
  end: 2009-08-20
fire_11387848:
  latitude: 57.520597430743365
  longitude: -129.41848556737727
  start: 2009-08-01
  end: 2009-08-06
fire_11385886:
  latitude: 56.18095454834265
  longitude: -127.67689635325232
  start: 2009-08-01
  end: 2009-08-10
fire_11159736:
  latitude: 59.62458937724064
  longitude: -126.60103433943758
  start: 2009-06-02
  end: 2009-06-12
fire_10914236:
  latitude: 52.56392094962092
  longitude: -122.32994572058848
  start: 2009-03-30
  end: 2009-04-13
fire_11253540:
  latitude: 52.669918775255425
  longitude: -124.96235086072124
  start: 2009-07-27
  end: 2009-08-07
fire_11253554:
  latitude: 52.19528875537406
  longitude: -125.84892673015774
  start: 2009-07-27
  end: 2009-08-14
fire_11253572:
  latitude: 50.70581443017531
  longitude: -122.02983107737616
  start: 2009-07-23
  end: 2009-08-05
fire_11386038:
  latitude: 50.99993871412429
  longitude: -122.20111462949092
  start: 2009-08-20
  end: 2009-09-09
fire_11253566:
  latitude: 51.014537037771014
  longitude: -122.48555133214704
  start: 2009-07-31
  end: 2009-08-07
fire_11253544:
  latitude: 52.52649190236332
  longitude: -125.84398341295996
  start: 2009-07-30
  end: 2009-08-14
fire_11385958:
  latitude: 53.101062334273486
  longitude: -124.33232069757425
  start: 2009-08-03
  end: 2009-08-15
fire_11385983:
  latitude: 51.91460975010648
  longitude: -123.78758220647649
  start: 2009-08-03
  end: 2009-09-23
fire_11386023:
  latitude: 51.084857048110955
  longitude: -121.86790387849808
  start: 2009-08-03
  end: 2009-09-03
fire_10914242:
  latitude: 51.55163313801661
  longitude: -122.64081216704392
  start: 2009-03-31
  end: 2009-04-23
fire_11539994:
  latitude: 51.11368857645432
  longitude: -122.50498816277567
  start: 2009-09-11
  end: 2009-09-25
fire_11097740:
  latitude: 50.92340843158798
  longitude: -122.67243228522209
  start: 2009-05-26
  end: 2009-06-16
fire_11253570:
  latitude: 50.83170454586169
  longitude: -122.22402085028264
  start: 2009-07-29
  end: 2009-08-11
fire_11386115:
  latitude: 49.77314843657789
  longitude: -120.90373743771052
  start: 2009-08-01
  end: 2009-08-11
fire_11386008:
  latitude: 51.33626313179053
  longitude: -124.16555652820432
  start: 2009-08-01
  end: 2009-08-21
fire_11386082:
  latitude: 50.327959093127895
  longitude: -121.974662153859
  start: 2009-08-09
  end: 2009-09-02
