output_bucket: firespreadpredictiontest
rectangular_size: 0.5
year: 2003
fire_3687426:
  latitude: 59.35506150856149
  longitude: -124.2469137902248
  start: 2003-09-27
  end: 2003-10-04
fire_3027501:
  latitude: 53.11048032750546
  longitude: -123.1328865287326
  start: 2003-03-11
  end: 2003-03-21
fire_3522070:
  latitude: 51.17930338561302
  longitude: -116.12188913972564
  start: 2003-08-14
  end: 2003-09-05
fire_3522029:
  latitude: 51.849958482147464
  longitude: -118.68435331085576
  start: 2003-08-14
  end: 2003-09-03
fire_3115998:
  latitude: 54.54690504317523
  longitude: -125.07197164818056
  start: 2003-04-14
  end: 2003-04-28
fire_3389161:
  latitude: 50.80625475210679
  longitude: -115.79544803552508
  start: 2003-07-29
  end: 2003-08-12
fire_3027497:
  latitude: 53.34276837403201
  longitude: -123.3324841601547
  start: 2003-03-15
  end: 2003-03-28
fire_3522072:
  latitude: 51.15832522416081
  longitude: -120.299937263177
  start: 2003-08-12
  end: 2003-08-25
fire_3522226:
  latitude: 49.47694635432014
  longitude: -117.06712610074209
  start: 2003-08-08
  end: 2003-08-23
fire_3522252:
  latitude: 49.23295143314435
  longitude: -115.45802718311737
  start: 2003-08-12
  end: 2003-09-06
fire_3522098:
  latitude: 51.064378593261075
  longitude: -120.08969972090556
  start: 2003-08-12
  end: 2003-08-27
fire_3684998:
  latitude: 51.44535687997696
  longitude: -119.75550179219128
  start: 2003-09-05
  end: 2003-09-22
fire_3522246:
  latitude: 49.32945528550993
  longitude: -116.5951266081306
  start: 2003-08-26
  end: 2003-09-22
fire_3523746:
  latitude: 59.940412394530135
  longitude: -120.62189067671709
  start: 2003-08-16
  end: 2003-08-21
fire_3390605:
  latitude: 59.85052462227698
  longitude: -120.62592201373104
  start: 2003-07-27
  end: 2003-08-10
fire_3687430:
  latitude: 58.96760514530751
  longitude: -123.52507317575972
  start: 2003-09-23
  end: 2003-10-04
fire_3522236:
  latitude: 49.34976661856163
  longitude: -115.9489067379236
  start: 2003-08-10
  end: 2003-09-04
fire_3522196:
  latitude: 50.025453129565776
  longitude: -117.96661529881004
  start: 2003-08-10
  end: 2003-08-27
fire_3389153:
  latitude: 51.14879657295497
  longitude: -120.20101844369452
  start: 2003-07-31
  end: 2003-08-16
fire_3522255:
  latitude: 49.147290457898904
  longitude: -114.69453718301284
  start: 2003-08-19
  end: 2003-09-01
fire_3938908:
  latitude: 55.19635629439595
  longitude: -120.93173374373032
  start: 2003-11-09
  end: 2003-11-22
fire_3522159:
  latitude: 50.545651365544565
  longitude: -117.15327774937352
  start: 2003-08-03
  end: 2003-08-26
fire_3522211:
  latitude: 49.7460335035959
  longitude: -119.53214185725938
  start: 2003-08-17
  end: 2003-09-08
fire_3522210:
  latitude: 49.80820259288991
  longitude: -117.08236107955432
  start: 2003-08-07
  end: 2003-08-19
fire_3522207:
  latitude: 49.84761503898575
  longitude: -115.01780988708028
  start: 2003-08-21
  end: 2003-09-05
fire_3522119:
  latitude: 50.77961214459945
  longitude: -120.27955204885204
  start: 2003-08-01
  end: 2003-08-10
fire_3522173:
  latitude: 50.469863270575765
  longitude: -119.4319508132043
  start: 2003-08-01
  end: 2003-08-09
fire_3522088:
  latitude: 51.06617857294347
  longitude: -116.0299119729799
  start: 2003-08-01
  end: 2003-08-21
fire_3523743:
  latitude: 59.94719531122483
  longitude: -120.36044748914908
  start: 2003-08-15
  end: 2003-08-28
fire_3523750:
  latitude: 59.89150798671957
  longitude: -120.59444094971498
  start: 2003-08-15
  end: 2003-08-21
fire_3522116:
  latitude: 50.78533286163912
  longitude: -119.81185862224122
  start: 2003-08-15
  end: 2003-09-08
fire_3522171:
  latitude: 50.39344519528741
  longitude: -115.18980674678136
  start: 2003-08-05
  end: 2003-08-22
fire_3389139:
  latitude: 52.031576767908405
  longitude: -124.28600320429784
  start: 2003-07-15
  end: 2003-07-23
fire_3522142:
  latitude: 50.67414177488223
  longitude: -121.4049971896569
  start: 2003-08-12
  end: 2003-08-30
fire_3389142:
  latitude: 51.695180817073734
  longitude: -123.89404059282276
  start: 2003-07-23
  end: 2003-08-19
fire_3522192:
  latitude: 50.10637680089384
  longitude: -121.67708590398432
  start: 2003-08-26
  end: 2003-09-11
fire_3522245:
  latitude: 49.29642250334815
  longitude: -119.47949664603486
  start: 2003-08-20
  end: 2003-09-02
