output_bucket: firespreadpredictiontest
rectangular_size: 0.5
year: 2018
fire_21999170:
  latitude: 49.49258859499539
  longitude: -118.03282600447142
  start: 2018-08-10
  end: 2018-09-06
fire_21999211:
  latitude: 49.154677348339554
  longitude: -116.83691565000574
  start: 2018-08-10
  end: 2018-09-01
fire_21999143:
  latitude: 49.88270660924817
  longitude: -117.22680245089758
  start: 2018-08-05
  end: 2018-08-28
fire_21998472:
  latitude: 57.67603309275255
  longitude: -130.986454023481
  start: 2018-08-13
  end: 2018-09-05
fire_22000345:
  latitude: 57.89361096293921
  longitude: -130.55887586024122
  start: 2018-08-13
  end: 2018-08-27
fire_21891265:
  latitude: 60.38008071981719
  longitude: -129.33730538187334
  start: 2018-07-04
  end: 2018-08-15
fire_22000115:
  latitude: 59.525022570642385
  longitude: -128.4679626130304
  start: 2018-08-01
  end: 2018-09-06
fire_22000200:
  latitude: 58.94124102118579
  longitude: -120.49656810670308
  start: 2018-08-01
  end: 2018-08-21
fire_21998556:
  latitude: 54.847834507121966
  longitude: -124.5740499779041
  start: 2018-08-01
  end: 2018-09-01
fire_21805293:
  latitude: 53.42823959388053
  longitude: -123.9410558801844
  start: 2018-06-22
  end: 2018-07-04
fire_21998798:
  latitude: 53.1476155648239
  longitude: -123.5077077570294
  start: 2018-08-09
  end: 2018-09-03
fire_21891293:
  latitude: 58.70007371241572
  longitude: -127.69852972570322
  start: 2018-07-29
  end: 2018-08-21
fire_21891302:
  latitude: 58.15897166899731
  longitude: -131.17298287046165
  start: 2018-07-29
  end: 2018-08-20
fire_21890475:
  latitude: 50.9891493152063
  longitude: -115.97521029471616
  start: 2018-07-29
  end: 2018-08-15
fire_21891307:
  latitude: 58.13365152660216
  longitude: -131.46194709142677
  start: 2018-07-29
  end: 2018-09-08
fire_21891297:
  latitude: 58.48703822527531
  longitude: -130.91008605188878
  start: 2018-07-29
  end: 2018-08-07
fire_21998549:
  latitude: 55.10716231388017
  longitude: -125.74850055004968
  start: 2018-08-17
  end: 2018-08-31
fire_21998529:
  latitude: 55.436267553094375
  longitude: -125.25619281981292
  start: 2018-08-17
  end: 2018-08-27
fire_21752685:
  latitude: 57.13860396326376
  longitude: -121.6869859871948
  start: 2018-05-21
  end: 2018-06-07
fire_21891317:
  latitude: 58.01409503179695
  longitude: -130.9798629966846
  start: 2018-07-31
  end: 2018-09-06
fire_21890410:
  latitude: 55.202211470115024
  longitude: -125.32695471044056
  start: 2018-07-31
  end: 2018-08-23
fire_21891287:
  latitude: 59.39203464124519
  longitude: -128.16119675802335
  start: 2018-07-31
  end: 2018-09-11
fire_21998485:
  latitude: 55.84235637854419
  longitude: -124.97618280560928
  start: 2018-08-16
  end: 2018-08-28
fire_21891322:
  latitude: 57.39633410008613
  longitude: -126.13074850004344
  start: 2018-07-27
  end: 2018-08-20
fire_21999191:
  latitude: 49.375468736866296
  longitude: -117.86759422328808
  start: 2018-08-15
  end: 2018-09-10
fire_22258616:
  latitude: 51.66652524453556
  longitude: -118.65716694296988
  start: 2018-10-22
  end: 2018-10-29
fire_22000114:
  latitude: 59.570352680859614
  longitude: -129.05206989154672
  start: 2018-08-23
  end: 2018-09-03
fire_22000013:
  latitude: 59.78627246187658
  longitude: -128.3459970852593
  start: 2018-08-03
  end: 2018-09-06
fire_22000362:
  latitude: 57.44132863069205
  longitude: -121.00943246840212
  start: 2018-08-03
  end: 2018-09-03
fire_21999235:
  latitude: 49.084746109425474
  longitude: -115.4337928610201
  start: 2018-08-11
  end: 2018-09-01
fire_22000250:
  latitude: 58.16599941497899
  longitude: -121.70860160019524
  start: 2018-08-19
  end: 2018-08-27
fire_21998926:
  latitude: 52.79915291390009
  longitude: -122.78238755049892
  start: 2018-08-07
  end: 2018-08-31
fire_21752684:
  latitude: 57.23297019831299
  longitude: -121.74604854156564
  start: 2018-05-22
  end: 2018-05-31
fire_21890503:
  latitude: 49.140841991603786
  longitude: -114.3107421862846
  start: 2018-07-29
  end: 2018-08-14
fire_21891284:
  latitude: 59.537348776137726
  longitude: -120.3278489571674
  start: 2018-07-09
  end: 2018-07-17
fire_21999109:
  latitude: 50.68077406962299
  longitude: -115.72056394241226
  start: 2018-08-06
  end: 2018-08-21
fire_21998539:
  latitude: 55.1538917953778
  longitude: -126.13328104721845
  start: 2018-08-06
  end: 2018-08-27
fire_21998490:
  latitude: 55.75296207690579
  longitude: -125.859479279908
  start: 2018-08-14
  end: 2018-09-01
fire_21998975:
  latitude: 52.413453930423955
  longitude: -118.52196462719095
  start: 2018-08-02
  end: 2018-08-24
fire_21999163:
  latitude: 49.543991502473226
  longitude: -116.4387705741428
  start: 2018-08-02
  end: 2018-08-31
fire_21998509:
  latitude: 55.598373345836144
  longitude: -127.18686576705944
  start: 2018-08-02
  end: 2018-08-22
fire_21999148:
  latitude: 49.79284072150205
  longitude: -121.09198508481404
  start: 2018-08-10
  end: 2018-08-30
fire_21998928:
  latitude: 52.765445248386754
  longitude: -124.41949794442718
  start: 2018-08-10
  end: 2018-09-03
fire_21999202:
  latitude: 49.18377095490158
  longitude: -120.33054558913412
  start: 2018-08-13
  end: 2018-09-09
fire_21998504:
  latitude: 55.698040199098465
  longitude: -127.7772721116255
  start: 2018-08-13
  end: 2018-09-04
fire_21998869:
  latitude: 52.93233382991798
  longitude: -125.11235690342131
  start: 2018-08-01
  end: 2018-08-20
fire_21998685:
  latitude: 53.80517866163683
  longitude: -125.5938047505945
  start: 2018-08-01
  end: 2018-09-11
fire_21998795:
  latitude: 53.143729001267495
  longitude: -123.77641325738952
  start: 2018-08-09
  end: 2018-09-06
fire_21997916:
  latitude: 50.27308148357476
  longitude: -127.08767763778648
  start: 2018-08-09
  end: 2018-08-23
fire_21890422:
  latitude: 53.93549210686995
  longitude: -125.20159778305543
  start: 2018-07-29
  end: 2018-08-29
fire_21890447:
  latitude: 52.86805800556461
  longitude: -126.16917547290666
  start: 2018-07-29
  end: 2018-09-06
fire_21890424:
  latitude: 53.9378045261824
  longitude: -126.7216792033828
  start: 2018-07-29
  end: 2018-09-03
fire_21999054:
  latitude: 51.73684187499921
  longitude: -125.32385107773892
  start: 2018-08-17
  end: 2018-09-02
fire_21997982:
  latitude: 49.93607234436005
  longitude: -126.9785101123303
  start: 2018-08-17
  end: 2018-09-04
fire_21997906:
  latitude: 50.34493105065016
  longitude: -127.16290856343394
  start: 2018-08-17
  end: 2018-09-03
fire_21999195:
  latitude: 49.2685322193943
  longitude: -120.2961770958307
  start: 2018-08-20
  end: 2018-09-11
fire_21999062:
  latitude: 51.44004187895275
  longitude: -121.863651505586
  start: 2018-08-08
  end: 2018-08-19
fire_22258640:
  latitude: 51.19013224939652
  longitude: -122.71992590942172
  start: 2018-10-15
  end: 2018-10-22
fire_21890417:
  latitude: 54.21421124698611
  longitude: -124.86775500553183
  start: 2018-07-27
  end: 2018-09-03
fire_21997943:
  latitude: 50.1563005770583
  longitude: -126.8847188696703
  start: 2018-08-12
  end: 2018-09-02
fire_21999004:
  latitude: 51.98580351296463
  longitude: -125.70736815071714
  start: 2018-08-15
  end: 2018-09-09
fire_22258634:
  latitude: 51.348272185790954
  longitude: -122.51235788105848
  start: 2018-10-18
  end: 2018-10-23
fire_21998652:
  latitude: 53.946011742010235
  longitude: -126.18825757184224
  start: 2018-08-19
  end: 2018-08-31
fire_22344390:
  latitude: 55.61008623368497
  longitude: -127.82453891911535
  start: 2018-11-03
  end: 2018-11-10
fire_21998730:
  latitude: 53.50211247962578
  longitude: -125.5070282420226
  start: 2018-08-07
  end: 2018-09-01
fire_21998747:
  latitude: 53.222968426122904
  longitude: -126.30709122539902
  start: 2018-08-07
  end: 2018-09-12
fire_21890488:
  latitude: 49.69173311963498
  longitude: -119.748527846058
  start: 2018-07-18
  end: 2018-07-23
fire_21890502:
  latitude: 49.10004525729122
  longitude: -119.81630686804873
  start: 2018-07-18
  end: 2018-08-30
fire_21890462:
  latitude: 51.860050291389705
  longitude: -125.8251636298038
  start: 2018-07-29
  end: 2018-08-12
fire_21890434:
  latitude: 53.361086849183096
  longitude: -124.41091764687152
  start: 2018-07-29
  end: 2018-09-03
fire_21999218:
  latitude: 49.139710588987086
  longitude: -121.18802921032064
  start: 2018-08-06
  end: 2018-08-25
fire_21999038:
  latitude: 51.782334726824686
  longitude: -125.49807530620888
  start: 2018-08-02
  end: 2018-08-29
