output_bucket: firespreadpredictiontest
rectangular_size: 0.5
year: 2011
fire_13508832:
  latitude: 59.65768558300038
  longitude: -129.24239645632213
  start: 2011-05-30
  end: 2011-06-16
fire_13446854:
  latitude: 59.81193883581514
  longitude: -129.23000315002912
  start: 2011-04-27
  end: 2011-05-07
fire_14173064:
  latitude: 51.79005846157612
  longitude: -123.46748445395885
  start: 2011-11-26
  end: 2011-12-08
fire_13368830:
  latitude: 51.699665979659606
  longitude: -122.81265370803766
  start: 2011-03-24
  end: 2011-04-03
