output_bucket: firespreadpredictiontest
rectangular_size: 0.5
year: 2015
fire_18158587:
  latitude: 56.37027814499908
  longitude: -124.97933196622196
  start: 2015-04-14
  end: 2015-05-15
fire_18301316:
  latitude: 59.617181617121226
  longitude: -121.35146545398707
  start: 2015-06-22
  end: 2015-07-04
fire_18301330:
  latitude: 59.49291164000282
  longitude: -127.62006620601964
  start: 2015-06-22
  end: 2015-07-17
fire_18301313:
  latitude: 59.680123149699185
  longitude: -124.42741495852223
  start: 2015-06-30
  end: 2015-07-20
fire_18301307:
  latitude: 59.75885793264528
  longitude: -120.25696691164896
  start: 2015-06-30
  end: 2015-07-08
fire_18301385:
  latitude: 58.685105489041426
  longitude: -123.0673209992556
  start: 2015-06-30
  end: 2015-07-18
fire_18236031:
  latitude: 58.47883584166133
  longitude: -125.23981711939834
  start: 2015-05-01
  end: 2015-05-25
fire_18391854:
  latitude: 56.38391257162513
  longitude: -123.78863217542757
  start: 2015-07-08
  end: 2015-07-23
fire_18301310:
  latitude: 59.68558282388789
  longitude: -120.7511672597864
  start: 2015-06-26
  end: 2015-07-06
fire_18235986:
  latitude: 58.97351467513863
  longitude: -126.67459129681488
  start: 2015-05-08
  end: 2015-05-28
fire_18301397:
  latitude: 58.20842449762935
  longitude: -126.80494243885988
  start: 2015-06-25
  end: 2015-07-19
fire_18301273:
  latitude: 60.15008309298953
  longitude: -121.88544997491634
  start: 2015-06-25
  end: 2015-07-06
fire_18235551:
  latitude: 53.74637123640288
  longitude: -123.51560214801944
  start: 2015-05-04
  end: 2015-05-27
fire_18301419:
  latitude: 57.90132078744502
  longitude: -120.10608553882128
  start: 2015-06-21
  end: 2015-07-14
fire_18235976:
  latitude: 59.25764726609187
  longitude: -132.50131719713448
  start: 2015-05-20
  end: 2015-05-27
fire_18236149:
  latitude: 55.81626860936456
  longitude: -122.43558315114733
  start: 2015-05-03
  end: 2015-05-18
fire_18235971:
  latitude: 59.51003303625984
  longitude: -127.771692909495
  start: 2015-05-31
  end: 2015-06-14
fire_18301276:
  latitude: 60.06771049055385
  longitude: -127.21583307774496
  start: 2015-06-28
  end: 2015-07-23
fire_18301407:
  latitude: 58.09616418100441
  longitude: -121.93913120793768
  start: 2015-06-28
  end: 2015-07-05
fire_18301303:
  latitude: 59.845860755400295
  longitude: -121.3172876603566
  start: 2015-06-24
  end: 2015-07-07
fire_18301351:
  latitude: 59.22632645762785
  longitude: -119.9218623881374
  start: 2015-06-24
  end: 2015-07-06
fire_18158614:
  latitude: 56.27169567987377
  longitude: -125.12155319006884
  start: 2015-04-28
  end: 2015-05-23
fire_18391645:
  latitude: 58.26804392870647
  longitude: -122.71695717242017
  start: 2015-07-05
  end: 2015-07-19
fire_18391561:
  latitude: 59.54300119201974
  longitude: -127.38972342620534
  start: 2015-07-05
  end: 2015-07-17
fire_18301325:
  latitude: 59.51214214835601
  longitude: -128.1962820965801
  start: 2015-06-23
  end: 2015-07-23
fire_18301309:
  latitude: 59.61581231449732
  longitude: -119.9548557336065
  start: 2015-06-23
  end: 2015-07-11
fire_18301379:
  latitude: 58.83710428237342
  longitude: -133.16017298509286
  start: 2015-06-23
  end: 2015-07-17
fire_18158588:
  latitude: 56.37889342307367
  longitude: -123.33283852243052
  start: 2015-04-24
  end: 2015-05-13
fire_18158546:
  latitude: 57.61835533393724
  longitude: -124.16745166389254
  start: 2015-04-24
  end: 2015-05-15
fire_18075701:
  latitude: 54.046938935728704
  longitude: -124.79466267296496
  start: 2015-03-23
  end: 2015-04-06
fire_18235984:
  latitude: 58.96510268594818
  longitude: -124.23754681461604
  start: 2015-05-30
  end: 2015-06-25
fire_18299235:
  latitude: 50.64052104469867
  longitude: -123.4226026439574
  start: 2015-06-22
  end: 2015-07-18
fire_18299251:
  latitude: 50.25720135907202
  longitude: -123.578947772093
  start: 2015-06-22
  end: 2015-07-21
fire_18388097:
  latitude: 52.2320443123517
  longitude: -124.01947138338188
  start: 2015-07-08
  end: 2015-07-19
fire_18525800:
  latitude: 49.13489008079411
  longitude: -118.98021531071458
  start: 2015-08-13
  end: 2015-08-22
fire_18388135:
  latitude: 49.92019725768584
  longitude: -121.88745842376436
  start: 2015-07-02
  end: 2015-07-15
fire_18075705:
  latitude: 53.13571579116817
  longitude: -123.82123259285386
  start: 2015-03-16
  end: 2015-03-30
fire_18075718:
  latitude: 52.121991636074746
  longitude: -122.46388332843408
  start: 2015-03-12
  end: 2015-03-31
fire_18525787:
  latitude: 49.48858405500267
  longitude: -121.88406632965676
  start: 2015-08-02
  end: 2015-08-06
fire_18299253:
  latitude: 50.179260968716584
  longitude: -121.61217790375356
  start: 2015-06-11
  end: 2015-06-19
