output_bucket: firespreadpredictiontest
rectangular_size: 0.5
year: 2021
fire_25295566:
  latitude: 51.08473482905707
  longitude: -118.86687384906018
  start: 2021-07-19
  end: 2021-08-15
fire_25411336:
  latitude: 52.649961946105805
  longitude: -120.40997054734952
  start: 2021-08-01
  end: 2021-08-19
fire_25087918:
  latitude: 56.68841773288916
  longitude: -121.36709185414138
  start: 2021-04-09
  end: 2021-04-17
fire_25206301:
  latitude: 56.27605537673506
  longitude: -125.40995100651328
  start: 2021-06-30
  end: 2021-07-23
fire_25295778:
  latitude: 49.32910595801235
  longitude: -116.8267161491288
  start: 2021-07-08
  end: 2021-08-06
fire_25206288:
  latitude: 57.15370930265474
  longitude: -121.8707040923071
  start: 2021-06-29
  end: 2021-07-08
fire_25206273:
  latitude: 57.80439062961194
  longitude: -122.84964871596704
  start: 2021-06-29
  end: 2021-07-06
fire_25295543:
  latitude: 51.339871601716936
  longitude: -119.332756776017
  start: 2021-07-07
  end: 2021-08-25
fire_25413145:
  latitude: 55.572597605097954
  longitude: -122.47650507412632
  start: 2021-08-12
  end: 2021-08-27
fire_25295628:
  latitude: 50.526095733917025
  longitude: -118.68801656272096
  start: 2021-07-23
  end: 2021-08-07
fire_25295385:
  latitude: 55.41672908779592
  longitude: -124.5128923181294
  start: 2021-07-03
  end: 2021-07-20
fire_25295376:
  latitude: 55.78913162619241
  longitude: -124.4820509975261
  start: 2021-07-03
  end: 2021-08-04
fire_25295504:
  latitude: 51.76231646005983
  longitude: -120.83224219034103
  start: 2021-07-03
  end: 2021-07-15
fire_25295544:
  latitude: 51.36301685961086
  longitude: -119.23269504486952
  start: 2021-07-31
  end: 2021-08-28
fire_25295548:
  latitude: 51.23795035771698
  longitude: -120.8725670395227
  start: 2021-07-11
  end: 2021-08-23
fire_25295637:
  latitude: 50.321295707011714
  longitude: -119.71998916710058
  start: 2021-07-14
  end: 2021-08-26
fire_25295438:
  latitude: 53.47625112800213
  longitude: -123.95688237027925
  start: 2021-07-02
  end: 2021-07-12
fire_25296581:
  latitude: 56.787394338749834
  longitude: -125.52467638076465
  start: 2021-07-02
  end: 2021-07-28
fire_25295409:
  latitude: 53.554258138335555
  longitude: -123.69147457240742
  start: 2021-07-10
  end: 2021-07-27
fire_25295738:
  latitude: 49.643087351976966
  longitude: -117.4290470100736
  start: 2021-07-10
  end: 2021-08-10
fire_25411428:
  latitude: 51.244623816832345
  longitude: -119.23204598358838
  start: 2021-08-07
  end: 2021-08-25
fire_25205667:
  latitude: 51.05109133127025
  longitude: -120.76825852495772
  start: 2021-06-28
  end: 2021-08-29
fire_25206280:
  latitude: 57.50399578801825
  longitude: -122.98460805770227
  start: 2021-06-28
  end: 2021-07-20
fire_25411294:
  latitude: 54.51598582129799
  longitude: -120.49860597764986
  start: 2021-08-06
  end: 2021-08-18
fire_25295769:
  latitude: 49.46287731846195
  longitude: -118.2117274381142
  start: 2021-07-17
  end: 2021-08-04
fire_25295672:
  latitude: 49.94983535026136
  longitude: -118.59215261373484
  start: 2021-07-17
  end: 2021-08-06
fire_25413143:
  latitude: 55.59826610249694
  longitude: -122.3912364558519
  start: 2021-08-14
  end: 2021-08-26
fire_25296551:
  latitude: 57.867001666548504
  longitude: -129.16566693810512
  start: 2021-07-05
  end: 2021-07-21
fire_25295766:
  latitude: 49.47151905448595
  longitude: -116.72091808515938
  start: 2021-07-13
  end: 2021-08-13
fire_25295775:
  latitude: 49.35407788862346
  longitude: -118.3379485342142
  start: 2021-07-13
  end: 2021-08-07
fire_25295699:
  latitude: 49.70222201881929
  longitude: -118.06665144623462
  start: 2021-07-13
  end: 2021-08-22
fire_25295740:
  latitude: 49.57786641670761
  longitude: -118.18952545363958
  start: 2021-07-13
  end: 2021-08-10
fire_25413166:
  latitude: 55.050738552912435
  longitude: -120.4371321839678
  start: 2021-08-10
  end: 2021-08-25
fire_25295489:
  latitude: 52.26705538938608
  longitude: -120.87057063505848
  start: 2021-07-01
  end: 2021-07-15
fire_25296598:
  latitude: 56.458132445487585
  longitude: -124.99475127908173
  start: 2021-07-01
  end: 2021-07-31
fire_25295488:
  latitude: 52.313004114487214
  longitude: -119.95901493349476
  start: 2021-07-29
  end: 2021-08-13
fire_25295490:
  latitude: 52.27854639039251
  longitude: -119.9258555790497
  start: 2021-07-29
  end: 2021-08-10
fire_25411390:
  latitude: 51.47297608657771
  longitude: -122.33411154718586
  start: 2021-08-01
  end: 2021-08-25
fire_25205706:
  latitude: 50.2690997830842
  longitude: -121.3101241676612
  start: 2021-06-29
  end: 2021-08-31
fire_25295714:
  latitude: 49.83285557130976
  longitude: -120.95693295466027
  start: 2021-07-15
  end: 2021-08-26
fire_25295541:
  latitude: 51.412879749176305
  longitude: -122.25008315077592
  start: 2021-07-03
  end: 2021-07-08
fire_25295425:
  latitude: 53.48863422721834
  longitude: -125.97709516736028
  start: 2021-07-03
  end: 2021-07-27
fire_25295454:
  latitude: 53.2194860121857
  longitude: -123.88630486962391
  start: 2021-07-03
  end: 2021-07-22
fire_25295774:
  latitude: 49.36286359059304
  longitude: -119.44255313385072
  start: 2021-07-11
  end: 2021-08-14
fire_25295611:
  latitude: 50.63231772879365
  longitude: -120.9515962676904
  start: 2021-07-14
  end: 2021-08-27
fire_25295662:
  latitude: 50.07050698704473
  longitude: -121.43453530658464
  start: 2021-07-14
  end: 2021-08-07
fire_25295395:
  latitude: 53.618908752903565
  longitude: -124.69149546521976
  start: 2021-07-02
  end: 2021-07-26
fire_25086449:
  latitude: 53.17986328951704
  longitude: -124.19053863747234
  start: 2021-04-05
  end: 2021-04-19
fire_25411297:
  latitude: 53.610223582370985
  longitude: -124.43513893428836
  start: 2021-08-07
  end: 2021-08-23
fire_25205672:
  latitude: 50.94655723451076
  longitude: -122.00794942148964
  start: 2021-06-28
  end: 2021-08-25
fire_25295493:
  latitude: 52.06875973731636
  longitude: -124.9976921058886
  start: 2021-07-06
  end: 2021-07-26
fire_25295513:
  latitude: 51.48460486338979
  longitude: -121.61792492999372
  start: 2021-07-09
  end: 2021-08-25
fire_25295790:
  latitude: 49.13966022715601
  longitude: -119.42155214020556
  start: 2021-07-17
  end: 2021-08-23
fire_25411326:
  latitude: 53.43256547925548
  longitude: -125.85466196541252
  start: 2021-08-02
  end: 2021-08-15
fire_25295785:
  latitude: 49.2130544213033
  longitude: -120.66600074069864
  start: 2021-07-21
  end: 2021-08-20
