output_bucket: firespreadpredictiontest
rectangular_size: 0.5
year: 2017
fire_20900899:
  latitude: 49.09887405580384
  longitude: -114.05704376760664
  start: 2017-08-30
  end: 2017-09-17
fire_20900894:
  latitude: 49.31221999687163
  longitude: -115.8830653888908
  start: 2017-08-30
  end: 2017-09-09
fire_20901733:
  latitude: 59.74230536265495
  longitude: -120.8484394108146
  start: 2017-08-10
  end: 2017-08-22
fire_20778132:
  latitude: 49.516011707925074
  longitude: -117.0045314048048
  start: 2017-07-21
  end: 2017-08-08
fire_20778064:
  latitude: 50.98561693266877
  longitude: -115.86112703607796
  start: 2017-07-10
  end: 2017-08-18
fire_20777926:
  latitude: 52.25603476234932
  longitude: -122.0185552787085
  start: 2017-07-09
  end: 2017-07-21
fire_20777908:
  latitude: 52.3292294792991
  longitude: -118.34865994686506
  start: 2017-07-09
  end: 2017-07-30
fire_20632729:
  latitude: 58.5727850572423
  longitude: -124.49144118355784
  start: 2017-05-10
  end: 2017-05-23
fire_20900860:
  latitude: 49.909129977954166
  longitude: -115.29891269888158
  start: 2017-08-13
  end: 2017-09-11
fire_20777932:
  latitude: 52.163960973107514
  longitude: -121.73958073589463
  start: 2017-07-12
  end: 2017-07-29
fire_20900861:
  latitude: 49.96085220987449
  longitude: -115.14444676228754
  start: 2017-08-29
  end: 2017-09-17
fire_20777740:
  latitude: 54.166526269117895
  longitude: -124.53053769413089
  start: 2017-07-08
  end: 2017-07-16
fire_20777927:
  latitude: 52.21540283171643
  longitude: -122.31146230265348
  start: 2017-07-08
  end: 2017-07-28
fire_20900829:
  latitude: 50.251260888252986
  longitude: -115.25627774888044
  start: 2017-08-08
  end: 2017-09-16
fire_20778122:
  latitude: 50.32365688380412
  longitude: -115.2221241308031
  start: 2017-07-27
  end: 2017-08-05
fire_20777930:
  latitude: 52.15662728354712
  longitude: -122.00783908506922
  start: 2017-07-07
  end: 2017-07-21
fire_20777892:
  latitude: 52.42854226318343
  longitude: -122.53385180344924
  start: 2017-07-07
  end: 2017-07-22
fire_20777853:
  latitude: 52.50665082439215
  longitude: -122.56736443682884
  start: 2017-07-07
  end: 2017-07-18
fire_20632721:
  latitude: 60.33919533176079
  longitude: -126.34235863493768
  start: 2017-05-28
  end: 2017-06-04
fire_21038855:
  latitude: 49.24401856009702
  longitude: -114.93406033276388
  start: 2017-09-01
  end: 2017-09-22
fire_20778043:
  latitude: 51.379775365522555
  longitude: -117.40796166916137
  start: 2017-07-26
  end: 2017-08-09
fire_20778025:
  latitude: 51.68194619510269
  longitude: -121.39322568186302
  start: 2017-07-02
  end: 2017-07-15
fire_20900813:
  latitude: 50.89024241485075
  longitude: -115.84688723317888
  start: 2017-08-27
  end: 2017-09-02
fire_20900516:
  latitude: 52.667716530273935
  longitude: -121.1904364469809
  start: 2017-08-07
  end: 2017-08-23
fire_20778093:
  latitude: 50.76435580501068
  longitude: -121.33542747193476
  start: 2017-07-05
  end: 2017-07-14
fire_20900739:
  latitude: 51.821475848210795
  longitude: -122.64462040701784
  start: 2017-08-13
  end: 2017-08-22
fire_20777971:
  latitude: 51.957401959772035
  longitude: -125.03715462579088
  start: 2017-07-04
  end: 2017-07-25
fire_20900335:
  latitude: 53.29832203855294
  longitude: -124.08170324873907
  start: 2017-08-01
  end: 2017-08-15
fire_20900644:
  latitude: 52.41008984827801
  longitude: -125.72490475188508
  start: 2017-08-01
  end: 2017-08-15
fire_20777774:
  latitude: 53.02577829791604
  longitude: -124.33268142568824
  start: 2017-07-08
  end: 2017-07-16
fire_20777897:
  latitude: 52.38757826068238
  longitude: -125.75825707781222
  start: 2017-07-08
  end: 2017-07-24
fire_20777944:
  latitude: 51.99799890899752
  longitude: -122.60669500978943
  start: 2017-07-08
  end: 2017-08-17
fire_20777760:
  latitude: 53.21570367105024
  longitude: -124.10454370952566
  start: 2017-07-08
  end: 2017-08-16
fire_20777746:
  latitude: 53.48541853944583
  longitude: -124.47320336168772
  start: 2017-07-08
  end: 2017-07-18
fire_20777753:
  latitude: 53.40029957744726
  longitude: -124.88787912011648
  start: 2017-07-07
  end: 2017-07-25
fire_20778003:
  latitude: 51.833143812072066
  longitude: -125.12187232432971
  start: 2017-07-07
  end: 2017-07-27
fire_20778131:
  latitude: 49.568165284324465
  longitude: -120.53462815946624
  start: 2017-07-07
  end: 2017-07-15
fire_20900703:
  latitude: 51.978422123909546
  longitude: -125.1293836455311
  start: 2017-08-04
  end: 2017-08-30
fire_20900724:
  latitude: 51.88270521197149
  longitude: -124.92435359097236
  start: 2017-08-04
  end: 2017-09-04
fire_20777838:
  latitude: 52.66261666730997
  longitude: -123.33183723227152
  start: 2017-07-15
  end: 2017-08-26
fire_21038845:
  latitude: 49.71868012748027
  longitude: -119.8244108470432
  start: 2017-09-01
  end: 2017-09-11
fire_20778047:
  latitude: 51.116047824894714
  longitude: -121.21562465704272
  start: 2017-07-06
  end: 2017-09-12
fire_20777771:
  latitude: 52.65662946476082
  longitude: -123.73004975780135
  start: 2017-07-06
  end: 2017-09-08
fire_20777943:
  latitude: 51.889928906283345
  longitude: -123.0264142615668
  start: 2017-07-06
  end: 2017-09-04
fire_20900712:
  latitude: 51.9336088001966
  longitude: -122.64313024203528
  start: 2017-08-03
  end: 2017-08-23
fire_21265157:
  latitude: 54.26478584678134
  longitude: -128.67886337584298
  start: 2017-11-07
  end: 2017-11-17
fire_21265146:
  latitude: 54.8740846795666
  longitude: -128.87970847303632
  start: 2017-11-07
  end: 2017-11-28
fire_20777743:
  latitude: 53.46959633769344
  longitude: -125.08526628987008
  start: 2017-07-18
  end: 2017-08-09
